### ISSUE TITLE
GV3 - Simulation Quit

### ISSUE THREAD

**Issue by FicelleYTB** [anatom3000/Gravit#12]
Petit bug je ne peut pas quitter la fenêtre quand on lance la simulation

OS: kali linux rolling

**Comment by anatom3000** [comment]
Je ne vois aucun problème 🤔 : tout ce passe normalement chez moi. Tu as utilisé le bouton de fermeture ou tu as fait un alt f4 ?

**Comment by anatom3000** [comment]
Oups... ah oui, en fait si... Je vois ça.

**Comment by anatom3000** [comment]
je l'ai fixé sans le savoir. pour les devs, j'ai juste ajouté pygame.quit() que j'avais ajouté :shushing_face:
