### ISSUE TITLE
Bug ne s'ouvre pas avec le cmd de windows

### ISSUE THREAD

**Issue by FicelleYTB** [anatom3000/Gravit#17]
Bah tout est dans le titre en faite mdr

**Comment by L-i-n-u-x-C-a-t** [comment]
Quelle commande tu as lancé et quel code d'erreur ça fait?

**Comment by FicelleYTB** [comment]
j'ai fais python3 main.py et dans le cmd ça fais rien même pas d'erreur

**Comment by L-i-n-u-x-C-a-t** [comment]
Et si tu fais ```py main.py?```

**Comment by anatom3000** [comment]
J'ai un Windows chez moi (et je m'en vante pas), je vais tester de mon coté 👍

**Comment by FicelleYTB** [comment]
Ok mdr j'aime bien le et je m'en vante pas

**Comment by FicelleYTB** [comment]
J'ai fais linux cat et ça fonctionne pas

**Comment by FicelleYTB** [comment]
bande de bâtard avec le et je suis idiot mdr

SI VOUS VOYER CE MESSAGE DANS UPDATE BAH DITE VOUS BIEN QUE ANATOM EST MECHANT

**Comment by L-i-n-u-x-C-a-t** [comment]
Alors? (Au pire essaye avec pyzo)

**Comment by anatom3000** [comment]
Bizarre... Je pense juste que Windows TRÈS TRÈS mal les libs de Python, etc...

**Comment by FicelleYTB** [comment]
Oui avec pyzo ça marche mais faudrait que ça marche directement avec le cmd

**Comment by FicelleYTB** [comment]
`print("donc vous me dites quand le bug est regler"`

**Comment by anatom3000** [comment]
Suit la issue et tu sera averti par mail quand elle sera fermée

**Comment by L-i-n-u-x-C-a-t** [comment]
Au pire, dans la version 1 on fera un py2exe, et ça devrait aller

**Comment by anatom3000** [comment]
Oui c'est prévu, on livrera une version *standalone* générée avec `pyinstaller` (qui est multi-plateforme)👍

**Comment by FicelleYTB** [comment]
o.O

**Comment by anatom3000** [comment]
Je ferme parce que ça se règlera tout seul quand on publirera la version PyInstaller/Py2Exe
