### ISSUE TITLE
GV2 - Impossible d'ouvrir une deuxième fois la simulation

### ISSUE THREAD

**Issue by L-i-n-u-x-C-a-t** [anatom3000/Gravit#8]
**Impossible d'ouvrir une deuxième fois la simulation**

on obtient : 
```
RuntimeError: threads can only be started once
```
Ce qui parait logique mais est embétant.

**Comment by anat3000** [comment]
OK, je vois ça dès que je peux

**Comment by anatom3000** [comment]
J'y travaille @L-i-n-u-x-C-a-t

**Comment by anatom3000** [comment]
C bon
